image: Visual Studio 2019

configuration: Release
platform: Any CPU

before_build:
- ps: ./ModifyVersion.ps1 $env:APPVEYOR_BUILD_FOLDER/src/BixShared.targets $env:APPVEYOR_BUILD_NUMBER
- cmd: nuget restore src\Bix.sln

build:
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'
  name: Bix Packages
  on:
    branch: master

deploy:
- provider: NuGet
  api_key:
    secure: GrDnIO6vODmya/PkBk8B7AbXIjFEjhcdTlnGL46nQ0OTR7qtkFbfVLTnEc6R2j9G
  artifact: Bix Packages
