image: Visual Studio 2019

configuration: Release
platform: Any CPU

before_build:
- ps: ./ModifyVersion.ps1 $env:APPVEYOR_BUILD_FOLDER/src/BixShared.targets $env:APPVEYOR_BUILD_NUMBER
- cmd: nuget restore src\Bix.sln

build:
  verbosity: minimal

artifacts:
- path: '**\*.*nupkg'
  name: Bix Packages

deploy:
- provider: NuGet
  api_key:
    secure: 0WJJyoL3KDd4D3PoaKD08XGwqWNjCbH2YM/gfFQNC79sWWrpWyV16DWPjEXELgZl
  artifact: Bix Packages
  on:
    branch: main
